// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    EBox: typeof import('elektro')['EBox']
    EContent: typeof import('elektro')['EContent']
    EDetailsList: typeof import('elektro')['EDetailsList']
    EEventInstance: typeof import('elektro')['EEventInstance']
    EImageSlider: typeof import('elektro')['EImageSlider']
    ELogo: typeof import('elektro')['ELogo']
    EProductionCard: typeof import('elektro')['EProductionCard']
    EStack: typeof import('elektro')['EStack']
    ETitle: typeof import('elektro')['ETitle']
    EWindowBorder: typeof import('elektro')['EWindowBorder']
    Fienta: typeof import('./src/components/Fienta.vue')['default']
    Header: typeof import('./src/components/Header.vue')['default']
    Island: typeof import('./node_modules/iles/dist/client/app/components/Island.vue')['default']
    Link: typeof import('./src/components/Link.vue')['default']
    Nav: typeof import('./src/components/Nav.vue')['default']
    Test: typeof import('./src/components/Test.vue')['default']
  }
}

export { }
